
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHAHEEL
 */
public class Main extends javax.swing.JFrame {

    private byte[] imageBytes;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollbar1 = new java.awt.Scrollbar();
        Header = new javax.swing.JPanel();
        SystemName = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        add_student = new javax.swing.JTabbedPane();
        addStudent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        std_dtls = new javax.swing.JLabel();
        Student_Details = new javax.swing.JPanel();
        sName = new javax.swing.JLabel();
        sAddress = new javax.swing.JLabel();
        sPhone = new javax.swing.JLabel();
        sNIC = new javax.swing.JLabel();
        sEmail = new javax.swing.JLabel();
        sFollowing = new javax.swing.JLabel();
        sDisability = new javax.swing.JLabel();
        std_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        std_address = new javax.swing.JTextArea();
        std_phone = new javax.swing.JTextField();
        std_email = new javax.swing.JTextField();
        std_nic = new javax.swing.JTextField();
        std_believes = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        std_disability = new javax.swing.JTextArea();
        sPhotoUpload = new javax.swing.JButton();
        std_pic = new javax.swing.JLabel();
        Gardient_Details = new javax.swing.JPanel();
        sName1 = new javax.swing.JLabel();
        sAddress1 = new javax.swing.JLabel();
        sPhone1 = new javax.swing.JLabel();
        sNIC1 = new javax.swing.JLabel();
        parent_name = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        parent_address = new javax.swing.JTextArea();
        parent_phone = new javax.swing.JTextField();
        parent_nic = new javax.swing.JTextField();
        part_dtls = new javax.swing.JLabel();
        Gardient_Details1 = new javax.swing.JPanel();
        sName2 = new javax.swing.JLabel();
        sAddress2 = new javax.swing.JLabel();
        sPhone2 = new javax.swing.JLabel();
        sNIC2 = new javax.swing.JLabel();
        std_reg_no = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        std_aca_year = new javax.swing.JComboBox<>();
        std_department = new javax.swing.JComboBox<>();
        std_faculty = new javax.swing.JComboBox<>();
        room_no = new javax.swing.JLabel();
        sPhone3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        generateRoomNumber = new javax.swing.JButton();
        submitForm = new javax.swing.JButton();
        resetForm = new javax.swing.JButton();
        part_dtls1 = new javax.swing.JLabel();
        viewStudent = new javax.swing.JPanel();
        listStudent = new javax.swing.JPanel();
        listRooms = new javax.swing.JPanel();
        leavedFromHostel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hostel Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setName("Hostel Management System"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1920, 800));
        setSize(new java.awt.Dimension(1920, 800));

        Header.setBackground(new java.awt.Color(51, 22, 142));
        Header.setForeground(new java.awt.Color(255, 255, 255));

        SystemName.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 48)); // NOI18N
        SystemName.setForeground(new java.awt.Color(255, 255, 255));
        SystemName.setText("Hostel Management System");
        SystemName.setIconTextGap(5);
        SystemName.setInheritsPopupMenu(false);

        Body.setBackground(new java.awt.Color(255, 255, 255));

        add_student.setBackground(new java.awt.Color(0, 51, 102));
        add_student.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add_student.setForeground(new java.awt.Color(255, 255, 255));
        add_student.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        add_student.setAutoscrolls(true);
        add_student.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N

        addStudent.setBackground(new java.awt.Color(255, 255, 255));
        addStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addStudent.setAutoscrolls(true);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        std_dtls.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        std_dtls.setText("STUDENT DETAILS");

        Student_Details.setBackground(new java.awt.Color(238, 235, 235));
        Student_Details.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 102)));

        sName.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sName.setText("Full Name");

        sAddress.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sAddress.setText("Address");

        sPhone.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sPhone.setText("Phone No.");

        sNIC.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sNIC.setText("NIC No.");

        sEmail.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sEmail.setText("Email Id.");

        sFollowing.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sFollowing.setText("Followings");

        sDisability.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sDisability.setText("Disability");

        std_name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_nameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel15.setText(":");

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel16.setText(":");

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel20.setText(":");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        std_address.setColumns(20);
        std_address.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_address.setRows(5);
        jScrollPane2.setViewportView(std_address);

        std_phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_phoneActionPerformed(evt);
            }
        });

        std_email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_emailActionPerformed(evt);
            }
        });

        std_nic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_nicActionPerformed(evt);
            }
        });

        std_believes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_believes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cristian", "Hindu", "Muslim", "Shinhalese" }));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        std_disability.setColumns(20);
        std_disability.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_disability.setRows(5);
        jScrollPane3.setViewportView(std_disability);

        sPhotoUpload.setBackground(new java.awt.Color(79, 89, 150));
        sPhotoUpload.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        sPhotoUpload.setForeground(new java.awt.Color(255, 255, 255));
        sPhotoUpload.setText("UPLOAD");
        sPhotoUpload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        sPhotoUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sPhotoUpload.setName(""); // NOI18N
        sPhotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPhotoUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Student_DetailsLayout = new javax.swing.GroupLayout(Student_Details);
        Student_Details.setLayout(Student_DetailsLayout);
        Student_DetailsLayout.setHorizontalGroup(
            Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                        .addComponent(sDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Student_DetailsLayout.createSequentialGroup()
                                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Student_DetailsLayout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(std_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(Student_DetailsLayout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(std_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(48, 48, 48)
                                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sFollowing, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(std_email)
                                            .addComponent(std_believes, 0, 300, Short.MAX_VALUE)))
                                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(std_name))
                                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2))))
                            .addGroup(Student_DetailsLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(std_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPhotoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        Student_DetailsLayout.setVerticalGroup(
            Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DetailsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(std_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(std_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sFollowing, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(std_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(std_believes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(std_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(sPhotoUpload))
                    .addGroup(Student_DetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Gardient_Details.setBackground(new java.awt.Color(238, 235, 235));
        Gardient_Details.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 102)));

        sName1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sName1.setText("Name");

        sAddress1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sAddress1.setText("Address");

        sPhone1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sPhone1.setText("Phone No.");

        sNIC1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sNIC1.setText("NIC No.");

        parent_name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        parent_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent_nameActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel22.setText(":");

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel23.setText(":");

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel24.setText(":");

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel28.setText(":");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        parent_address.setColumns(20);
        parent_address.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        parent_address.setRows(5);
        jScrollPane4.setViewportView(parent_address);

        parent_phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        parent_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent_phoneActionPerformed(evt);
            }
        });

        parent_nic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        parent_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent_nicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Gardient_DetailsLayout = new javax.swing.GroupLayout(Gardient_Details);
        Gardient_Details.setLayout(Gardient_DetailsLayout);
        Gardient_DetailsLayout.setHorizontalGroup(
            Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gardient_DetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sName1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Gardient_DetailsLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(parent_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(sNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parent_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Gardient_DetailsLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(parent_name))
                    .addGroup(Gardient_DetailsLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        Gardient_DetailsLayout.setVerticalGroup(
            Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gardient_DetailsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sName1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parent_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Gardient_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parent_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parent_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        part_dtls.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        part_dtls.setText("PARENT/GUARDIAN DETAILS");

        Gardient_Details1.setBackground(new java.awt.Color(238, 235, 235));
        Gardient_Details1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 102)));

        sName2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sName2.setText("Reg No.");

        sAddress2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sAddress2.setText("Faculty");

        sPhone2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sPhone2.setText("ACA. Year");

        sNIC2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sNIC2.setText("Depmnt");

        std_reg_no.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_reg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_reg_noActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel25.setText(":");

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel26.setText(":");

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel27.setText(":");

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel29.setText(":");

        std_aca_year.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_aca_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023" }));
        std_aca_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_aca_yearActionPerformed(evt);
            }
        });

        std_department.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "FOT", "FOE", "FMC", "FIA", "FAC" }));
        std_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_departmentActionPerformed(evt);
            }
        });

        std_faculty.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        std_faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "FOT", "FOE", "FMC", "FIA", "FAC" }));
        std_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_facultyActionPerformed(evt);
            }
        });

        room_no.setBackground(new java.awt.Color(102, 102, 255));
        room_no.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        room_no.setForeground(new java.awt.Color(204, 0, 51));
        room_no.setText("Room No");

        sPhone3.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        sPhone3.setText("ACA. Year");

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel30.setText(":");

        generateRoomNumber.setBackground(new java.awt.Color(255, 255, 51));
        generateRoomNumber.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        generateRoomNumber.setText("ROOM NO");
        generateRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRoomNumberActionPerformed(evt);
            }
        });

        submitForm.setBackground(new java.awt.Color(204, 255, 255));
        submitForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        submitForm.setText("SUBMIT");
        submitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFormActionPerformed(evt);
            }
        });

        resetForm.setBackground(new java.awt.Color(255, 204, 204));
        resetForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resetForm.setText("RESET");
        resetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Gardient_Details1Layout = new javax.swing.GroupLayout(Gardient_Details1);
        Gardient_Details1.setLayout(Gardient_Details1Layout);
        Gardient_Details1Layout.setHorizontalGroup(
            Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gardient_Details1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gardient_Details1Layout.createSequentialGroup()
                        .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sName2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(std_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Gardient_Details1Layout.createSequentialGroup()
                        .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Gardient_Details1Layout.createSequentialGroup()
                                .addComponent(sPhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(std_aca_year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(room_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85)
                .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gardient_Details1Layout.createSequentialGroup()
                        .addComponent(generateRoomNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitForm))
                    .addGroup(Gardient_Details1Layout.createSequentialGroup()
                        .addComponent(sAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(std_faculty, 0, 300, Short.MAX_VALUE))
                    .addGroup(Gardient_Details1Layout.createSequentialGroup()
                        .addComponent(sNIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(std_department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(345, 345, 345))
        );
        Gardient_Details1Layout.setVerticalGroup(
            Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gardient_Details1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sName2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_aca_year, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_department, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Gardient_Details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_no)
                    .addComponent(generateRoomNumber)
                    .addComponent(submitForm)
                    .addComponent(resetForm))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        part_dtls1.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        part_dtls1.setText("ACADEMIC DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Student_Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(part_dtls1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(std_dtls, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gardient_Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(part_dtls, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gardient_Details1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(std_dtls)
                .addGap(18, 18, 18)
                .addComponent(Student_Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(part_dtls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gardient_Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(part_dtls1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gardient_Details1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout addStudentLayout = new javax.swing.GroupLayout(addStudent);
        addStudent.setLayout(addStudentLayout);
        addStudentLayout.setHorizontalGroup(
            addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        addStudentLayout.setVerticalGroup(
            addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add_student.addTab("Add Student", addStudent);

        javax.swing.GroupLayout viewStudentLayout = new javax.swing.GroupLayout(viewStudent);
        viewStudent.setLayout(viewStudentLayout);
        viewStudentLayout.setHorizontalGroup(
            viewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );
        viewStudentLayout.setVerticalGroup(
            viewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        add_student.addTab("View Student", viewStudent);

        listStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        javax.swing.GroupLayout listStudentLayout = new javax.swing.GroupLayout(listStudent);
        listStudent.setLayout(listStudentLayout);
        listStudentLayout.setHorizontalGroup(
            listStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );
        listStudentLayout.setVerticalGroup(
            listStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        add_student.addTab("List Students", listStudent);

        javax.swing.GroupLayout listRoomsLayout = new javax.swing.GroupLayout(listRooms);
        listRooms.setLayout(listRoomsLayout);
        listRoomsLayout.setHorizontalGroup(
            listRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );
        listRoomsLayout.setVerticalGroup(
            listRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        add_student.addTab("List Rooms", listRooms);

        javax.swing.GroupLayout leavedFromHostelLayout = new javax.swing.GroupLayout(leavedFromHostel);
        leavedFromHostel.setLayout(leavedFromHostelLayout);
        leavedFromHostelLayout.setHorizontalGroup(
            leavedFromHostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );
        leavedFromHostelLayout.setVerticalGroup(
            leavedFromHostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        add_student.addTab("Leave from Hostel", leavedFromHostel);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_student)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_student, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SystemName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SystemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 1760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void std_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_nameActionPerformed

    private void std_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_phoneActionPerformed

    private void std_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_emailActionPerformed

    private void std_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_nicActionPerformed

    private void parent_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parent_nameActionPerformed

    private void parent_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parent_phoneActionPerformed

    private void parent_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parent_nicActionPerformed

    private void std_reg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_reg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_reg_noActionPerformed

    private void std_aca_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_aca_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_aca_yearActionPerformed

    private void std_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_departmentActionPerformed

    private void std_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_facultyActionPerformed

    private void sPhotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPhotoUploadActionPerformed
        // TODO add your handling code here:
        
         JFileChooser fileChoose = new JFileChooser();
    int result = fileChoose.showOpenDialog(null);
    
    // Check if the user selected a file
    if (result == JFileChooser.APPROVE_OPTION) {
        File f = fileChoose.getSelectedFile();
        String path = f.getAbsolutePath();
        
        try {
            // Read and scale the image
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(182, 220, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos); // Assuming the image is in JPG format
            baos.flush();
            this.imageBytes = baos.toByteArray();
            baos.close();
            
            // Set the image to a JLabel
            std_pic.setIcon(icon);
        } catch (IOException ex) {
            // Log the exception
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        System.out.println("File selection cancelled.");
    }
    }//GEN-LAST:event_sPhotoUploadActionPerformed

    private void generateRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateRoomNumberActionPerformed
        // TODO add your handling code here:
       
        String roomNo = null;
        try {
            roomNo = String.valueOf(Actions.getAvailableRoom());
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        room_no.setText(roomNo);
        this.generateRoomNumber.setEnabled(false);
         JOptionPane.showMessageDialog(null, "Your Room No is : " + roomNo);
        
    }//GEN-LAST:event_generateRoomNumberActionPerformed

    private void submitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFormActionPerformed
        // TODO add your handling code here:
        if(!validateFields()){
             JOptionPane.showMessageDialog(null, "Please Check your inputs...", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String stdName = std_name.getText();
            String stdAddress = std_address.getText();
            String stdPhone = std_phone.getText();
            String stdEmail = std_email.getText();
            String stdNic = std_nic.getText();
            String stdBelieves = std_believes.getSelectedItem().toString();
            String parentName = parent_name.getText();
            String parentAddress = parent_address.getText();
            String parentPhone = parent_phone.getText();
            String parentNic = parent_nic.getText();
            String stdRegNo = std_reg_no.getText();
            String stdFaculty = std_faculty.getSelectedItem().toString();
            String stdAcaYear = std_aca_year.getSelectedItem().toString();
            String stdDepartment = std_department.getSelectedItem().toString();
            String roomNo = room_no.getText().toString();
            
            
            
        }
        
        
    }//GEN-LAST:event_submitFormActionPerformed
    
    //Reqex Validation for Phone numbers - Used ChatGPT
     public boolean isValidSriLankaPhoneNumber(String phoneNumber) {
        String mobileRegex = "^07\\d{8}$";  // Validates mobile numbers like 0771234567
        String landlineRegex = "^(0[1-9]{1}[0-9]{1,2})\\d{7}$";  // Validates landline numbers like 0112345678
        
        Pattern mobilePattern = Pattern.compile(mobileRegex);
        Pattern landlinePattern = Pattern.compile(landlineRegex);
        
        Matcher mobileMatcher = mobilePattern.matcher(phoneNumber);
        Matcher landlineMatcher = landlinePattern.matcher(phoneNumber);
        
        return mobileMatcher.matches() || landlineMatcher.matches();
    }
    // Validate Email - GPT
      public boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(emailRegex);
    }
     
      //Valicate NIC
     public boolean isValidNIC(String nic) {
        // Regex for old NIC (9 digits followed by a letter V or X)
        String oldNicRegex = "^[0-9]{9}[VX]$";
        // Regex for new NIC (exactly 12 digits with no letter)
        String newNicRegex = "^[0-9]{12}$";

        // Check if NIC matches either old or new format
        return nic.matches(oldNicRegex) || nic.matches(newNicRegex);
    }

      
     //Return true when all field are filled 
    private boolean isAllEmpty(){
       return !(std_name.getText().isEmpty() && std_address.getText().isEmpty() && std_phone.getText().isEmpty() && std_email.getText().isEmpty()
               && std_nic.getText().isEmpty() && std_believes.getSelectedItem().equals(" ") && parent_name.getText().isEmpty() && parent_address.getText().isEmpty() &&
               parent_phone.getText().isEmpty() && parent_nic.getText().isEmpty() && std_reg_no.getText().isEmpty() && std_faculty.getSelectedItem().equals(" ") &&
               std_aca_year.getSelectedItem().equals(" ") && std_department.getSelectedItem().equals(" "));
    }
    
    public boolean validateFields() {
        // Getting the values from the fields (assuming text fields for name, address, etc.)
        String stdName = std_name.getText();
        String stdAddress = std_address.getText();
        String stdPhone = std_phone.getText();
        String stdEmail = std_email.getText();
        String stdNic = std_nic.getText();
        String stdBelieves = std_believes.getSelectedItem().toString();
        String parentName = parent_name.getText();
        String parentAddress = parent_address.getText();
        String parentPhone = parent_phone.getText();
        String parentNic = parent_nic.getText();
        String stdRegNo = std_reg_no.getText();
        String stdFaculty = std_faculty.getSelectedItem().toString();
        String stdAcaYear = std_aca_year.getSelectedItem().toString();
        String stdDepartment = std_department.getSelectedItem().toString();

        // Validation for required fields
        if (stdName.isEmpty() || stdAddress.isEmpty() || stdPhone.isEmpty() || stdEmail.isEmpty() || stdNic.isEmpty()
            || stdBelieves.trim().equals("") || parentName.isEmpty() || parentAddress.isEmpty() || parentPhone.isEmpty()
            || parentNic.isEmpty() || stdRegNo.isEmpty() || stdFaculty.trim().equals("") || stdAcaYear.trim().equals("")
            || stdDepartment.trim().equals("")) {
            return false;  // Return false if any required field is empty
        }

        // Validate phone numbers
        if (!isValidSriLankaPhoneNumber(stdPhone)) {
            return false;  // Invalid phone number
        }
        if (!isValidSriLankaPhoneNumber(parentPhone)) {
            return false;  // Invalid parent phone number
        }

        // Validate email
        if (!isValidEmail(stdEmail)) {
            return false;  // Invalid email
        }

        // Validate NIC
        if (!isValidNIC(stdNic)) {
            return false;  // Invalid student NIC
        }
        if (!isValidNIC(parentNic)) {
            return false;  // Invalid parent NIC
        }

        // All fields are valid
        return true;
    }
    
    
    private void resetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Gardient_Details;
    private javax.swing.JPanel Gardient_Details1;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Student_Details;
    private javax.swing.JLabel SystemName;
    private javax.swing.JPanel addStudent;
    private javax.swing.JTabbedPane add_student;
    private javax.swing.JButton generateRoomNumber;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel leavedFromHostel;
    private javax.swing.JPanel listRooms;
    private javax.swing.JPanel listStudent;
    private javax.swing.JTextArea parent_address;
    private javax.swing.JTextField parent_name;
    private javax.swing.JTextField parent_nic;
    private javax.swing.JTextField parent_phone;
    private javax.swing.JLabel part_dtls;
    private javax.swing.JLabel part_dtls1;
    private javax.swing.JButton resetForm;
    private javax.swing.JLabel room_no;
    private javax.swing.JLabel sAddress;
    private javax.swing.JLabel sAddress1;
    private javax.swing.JLabel sAddress2;
    private javax.swing.JLabel sDisability;
    private javax.swing.JLabel sEmail;
    private javax.swing.JLabel sFollowing;
    private javax.swing.JLabel sNIC;
    private javax.swing.JLabel sNIC1;
    private javax.swing.JLabel sNIC2;
    private javax.swing.JLabel sName;
    private javax.swing.JLabel sName1;
    private javax.swing.JLabel sName2;
    private javax.swing.JLabel sPhone;
    private javax.swing.JLabel sPhone1;
    private javax.swing.JLabel sPhone2;
    private javax.swing.JLabel sPhone3;
    private javax.swing.JButton sPhotoUpload;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JComboBox<String> std_aca_year;
    private javax.swing.JTextArea std_address;
    private javax.swing.JComboBox<String> std_believes;
    private javax.swing.JComboBox<String> std_department;
    private javax.swing.JTextArea std_disability;
    private javax.swing.JLabel std_dtls;
    private javax.swing.JTextField std_email;
    private javax.swing.JComboBox<String> std_faculty;
    private javax.swing.JTextField std_name;
    private javax.swing.JTextField std_nic;
    private javax.swing.JTextField std_phone;
    private javax.swing.JLabel std_pic;
    private javax.swing.JTextField std_reg_no;
    private javax.swing.JButton submitForm;
    private javax.swing.JPanel viewStudent;
    // End of variables declaration//GEN-END:variables
}
